title: RA_1013_access_vulnerability_management_system_logs
id: RA1013
description: >
  Access vulnerability management system logs. It will help to identify the vulnerabilities a specific host had at a specific time in the past
author: your name/nickname/twitter
creation_date: YYYY/MM/DD
stage: preparation
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
