title: RA_2106_analyse_uri
id: RA2106
description: >
  Analyse an URI
author: name/nickname/twitter
creation_date: YYYY/MM/DD
stage: identification
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
