title: RA_3301_quarantine_file_by_format
id: RA3301
description: >
  Quarantine a file by its format
author: your name/nickname/twitter
creation_date: YYYY/MM/DD
stage: containment
automation:
  - thehive/phantom/demisto/etc
references:
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
