title: RA_4001_report_incident_to_external_companies
id: RA4001
description: Report incident to external companies
author: '@atc_project'
creation_date: 2019/01/31
stage: eradication
automation:
  - thehive                 # integration with MISP
references: 
  - https://www.antiphishing.org/report-phishing/
  - https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en
  - https://www.ic3.gov/default.aspx
  - http://www.us-cert.gov/nav/report_phishing.html
  - https://blog.thehive-project.org/2017/06/19/thehive-cortex-and-misp-how-they-all-fit-together/
  - https://www.sei.cmu.edu/education-outreach/computer-security-incident-response-teams/national-csirts/
  - https://www.crowdstrike.com/blog/indicators-attack-vs-indicators-compromise/
  - https://mitre.github.io/unfetter/about/
workflow: |
  Report incident to external security companites, i.e. [National Computer Security Incident Response Teams (CSIRTs)](https://www.sei.cmu.edu/education-outreach/computer-security-incident-response-teams/national-csirts/).  
  Provide all Indicators of Compromise and Indicators of Attack that have been observed.  
  
  A phishing attack could be reported to:  

  1. [National Computer Security Incident Response Teams (CSIRTs)](https://www.sei.cmu.edu/education-outreach/computer-security-incident-response-teams/national-csirts/)  
  2. [U.S. government-operated website](http://www.us-cert.gov/nav/report_phishing.html)  
  3. [Anti-Phishing Working Group (APWG)](http://antiphishing.org/report-phishing/)  
  4. [Google Safe Browsing](https://safebrowsing.google.com/safebrowsing/report_phish/?hl=en)  
  5. [The FBI's Intenet Crime Complaint Center (IC3)](https://www.ic3.gov/default.aspx)  

  This Response Action could be automated with [TheHive and MISP integration](https://blog.thehive-project.org/2017/06/19/thehive-cortex-and-misp-how-they-all-fit-together/).  
