title: RA_5001_reinstall_host_from_golden_image
id: RA5001
description: >
  Reinstall host OS from a golden image
author: name/nickname/twitter
creation_date: YYYY/MM/DD
stage: recovery
automation:
  - thehive
references: 
  - https://example.com
workflow: |
  Description of the workflow for the Response Action in markdown format.  
  Here newlines will be saved.  
