ra_mapping = {
    "RA1001": "Practice",
    "RA1002": "Take Trainings",
    "RA1003": "Raise Personnel Awareness",
    "RA1004": "Make Personnel Report Suspicious Activity",
    "RA1005": "Set Up Relevant Data Collection",
    "RA1006": "Set Up Centralized Long-term Log Storage",
    "RA1007": "Develop Communication Map",
    "RA1008": "Make Sure There Are Backups",
    "RA1009": "Get Network Architecture Map",
    "RA1010": "Get Access Control Matrix",
    "RA1011": "Develop Assets Knowledge Base",
    "RA1012": "Check Analysis Toolset",
    "RA1013": "Access Vulnerability Management System Logs",
    "RA1014": "Connect with Trusted Communities",
    "RA1101": "Access External Network Flow Logs",
    "RA1102": "Access Internal Network Flow Logs",
    "RA1103": "Access Internal HTTP Logs",
    "RA1104": "Access External HTTP Logs",
    "RA1105": "Access Internal DNS Logs",
    "RA1106": "Access External DNS Logs",
    "RA1107": "Access VPN Logs",
    "RA1108": "Access DHCP Logs",
    "RA1109": "Access Internal Packet Capture Data",
    "RA1110": "Access External Packet Capture Data",
    "RA1111": "Get Ability to Block External IP Address",
    "RA1112": "Get Ability to Block Internal IP Address",
    "RA1113": "Get Ability to Block External Domain",
    "RA1114": "Get Ability to Block Internal Domain",
    "RA1115": "Get Ability to Block External URL",
    "RA1116": "Get Ability to Block Internal URL",
    "RA1117": "Get Ability to Block Port External Communication",
    "RA1118": "Get Ability to Block Port Internal Communication",
    "RA1119": "Get Ability to Block User External Communication",
    "RA1120": "Get Ability to Block User Internal Communication",
    "RA1121": "Get Ability to Find Data Transferred by Content Pattern",
    "RA1122": "Get Ability to Block Data Transferring by Content Pattern",
    "RA1123": "Get Ability to List Data Transferred",
    "RA1124": "Get Ability to Collect Transferred Data",
    "RA1125": "Get Ability to Identify Transferred Data",
    "RA1126": "Find Data Transferred by Content Pattern",
    "RA1127": "Get Ability to Analyse User-agent",
    "RA1201": "Get Ability to List Users Opened Email Message",
    "RA1202": "Get Ability to List Email Message Receivers",
    "RA1203": "Get Ability to Block Email Domain",
    "RA1204": "Get Ability to Block Email Sender",
    "RA1205": "Get Ability to Delete Email Message",
    "RA1206": "Get Ability to Quarantine Email Message",
    "RA1207": "Get Ability to Collect Email Message",
    "RA1208": "Get Ability to Analyse Email Address",
    "RA1301": "Get Ability to List Files Created",
    "RA1302": "Get Ability to List Files Modified",
    "RA1303": "Get Ability to List Files Deleted",
    "RA1304": "Get Ability to List Files Downloaded",
    "RA1305": "Get Ability to List Files with Tampered Timestamps",
    "RA1306": "Get Ability to Find File by Path",
    "RA1307": "Get Ability to Find File by Metadata",
    "RA1308": "Get Ability to Find File by Hash",
    "RA1309": "Get Ability to Find File by Format",
    "RA1310": "Get Ability to Find File by Content Pattern",
    "RA1311": "Get Ability to Collect File",
    "RA1312": "Get Ability to Quarantine File by Path",
    "RA1313": "Get Ability to Quarantine File by Hash",
    "RA1314": "Get Ability to Quarantine File by Format",
    "RA1315": "Get Ability to Quarantine File by Content Pattern",
    "RA1316": "Get Ability to Remove File",
    "RA1317": "Get Ability to Analyse File Hash",
    "RA1318": "Get Ability to Analyse Windows PE",
    "RA1319": "Get Ability to Analyse macOS Mach-O",
    "RA1320": "Get Ability to Analyse Unix ELF",
    "RA1321": "Get Ability to Analyse MS Office File",
    "RA1322": "Get Ability to Analyse PDF File",
    "RA1323": "Get Ability to Analyse Script",
    "RA1324": "Get Ability to Analyse JAR",
    "RA1325": "Get Ability to Analyse Filename",
    "RA1401": "Get Ability to List Processes Executed",
    "RA1402": "Get Ability to Find Process by Executable Path",
    "RA1403": "Get Ability to Find Process by Executable Metadata",
    "RA1404": "Get Ability to Find Process by Executable Hash",
    "RA1405": "Get Ability to Find Process by Executable Format",
    "RA1406": "Get Ability to Find Process by Executable Content Pattern",
    "RA1407": "Get Ability to Block Process by Executable Path",
    "RA1408": "Get Ability to Block Process by Executable Metadata",
    "RA1409": "Get Ability to Block Process by Executable Hash",
    "RA1410": "Get Ability to Block Process by Executable Format",
    "RA1411": "Get Ability to Block Process by Executable Content Pattern",
    "RA1501": "Manage Remote Computer Management System Policies",
    "RA1502": "Get Ability to List Registry Keys Modified",
    "RA1503": "Get Ability to List Registry Keys Deleted",
    "RA1504": "Get Ability to List Registry Keys Accessed",
    "RA1505": "Get Ability to List Registry Keys Created",
    "RA1506": "Get Ability to List Services Created",
    "RA1507": "Get Ability to List Services Modified",
    "RA1508": "Get Ability to List Services Deleted",
    "RA1509": "Get Ability to Remove Registry Key",
    "RA1510": "Get Ability to Remove Service",
    "RA1511": "Get Ability to Analyse Registry Key",
    "RA1601": "Manage Identity Management System",
    "RA1602": "Get Ability to Lock User Account",
    "RA1603": "Get Ability to List Users Authenticated",
    "RA1604": "Get Ability to Revoke Authentication Credentials",
    "RA1605": "Get Ability to Remove User Account",
    "RA2001": "List Victims Of Security Alert",
    "RA2002": "List Host Vulnerabilities",
    "RA2003": "Put Compromised Accounts on Monitoring",
    "RA2101": "List Hosts Communicated with Internal Domain",
    "RA2102": "List Hosts Communicated with Internal IP",
    "RA2103": "List Hosts Communicated with Internal URL",
    "RA2104": "Analyse Domain Name",
    "RA2105": "RA_2105_analyse_IP",
    "RA2106": "Analyse URI",
    "RA2107": "List Hosts Communicated by Port",
    "RA2108": "List Hosts Connected to VPN",
    "RA2109": "List Hosts Connected to Intranet",
    "RA2110": "List Data Transferred",
    "RA2111": "Collect Transferred Data",
    "RA2112": "Identify Transferred Data",
    "RA2113": "List Hosts Communicated with External Domain",
    "RA2114": "List Hosts Communicated with External IP",
    "RA2115": "List Hosts Communicated with External URL",
    "RA2116": "Find Data Transferred by Content Pattern",
    "RA2117": "Analyse User-Agent",
    "RA2201": "List Users Opened Email Message",
    "RA2202": "Collect Email Message",
    "RA2203": "List Email Message Receivers",
    "RA2204": "Make Sure Email Message is Phishing",
    "RA2205": "Extract Observables from Email Message",
    "RA2206": "Analyse Email Address",
    "RA2301": "List Files Created",
    "RA2302": "List Files Modified",
    "RA2303": "List Files Deleted",
    "RA2304": "List Files Downloaded",
    "RA2305": "List Files with Tampered Timestamps",
    "RA2306": "Find File by Path",
    "RA2307": "Find File by Metadata",
    "RA2308": "Find File by Hash",
    "RA2309": "Find File by Format",
    "RA2310": "Find File by Content Pattern",
    "RA2311": "Collect File",
    "RA2312": "Analyse File Hash",
    "RA2313": "Analyse Windows PE",
    "RA2314": "Analyse macOS Mach-O",
    "RA2315": "Analyse Unix ELF",
    "RA2316": "Analyse MS Office File",
    "RA2317": "Analyse PDF File",
    "RA2318": "Analyse Script",
    "RA2319": "Analyse JAR",
    "RA2320": "Analyse Filename",
    "RA2401": "List Processes Executed",
    "RA2402": "Find Process by Executable Path",
    "RA2403": "Find Process by Executable Metadata",
    "RA2404": "Find Process by Executable Hash",
    "RA2405": "Find Process by Executable Format",
    "RA2406": "Find Process by Executable Content Pattern",
    "RA2501": "List Registry Keys Modified",
    "RA2502": "List Registry Keys Deleted",
    "RA2503": "List Registry Keys Accessed",
    "RA2504": "List Registry Keys Created",
    "RA2505": "List Services Created",
    "RA2506": "List Services Modified",
    "RA2507": "List Services Deleted",
    "RA2508": "Analyse Registry Key",
    "RA2601": "List Users Authenticated",
    "RA3001": "Patch Vulnerability",
    "RA3101": "Block External IP Address",
    "RA3102": "Block Internal IP Address",
    "RA3103": "Block External Domain",
    "RA3104": "Block Internal Domain",
    "RA3105": "Block External URL",
    "RA3106": "Block Internal URL",
    "RA3107": "Block Port External Communication",
    "RA3108": "Block Port Internal Communication",
    "RA3109": "Block User External Communication",
    "RA3110": "Block User Internal Communication",
    "RA3111": "Block Data Transferring by Content Pattern",
    "RA3201": "Block Domain on Email",
    "RA3202": "Block Sender on Email",
    "RA3203": "Quarantine Email Message",
    "RA3301": "Quarantine File by Format",
    "RA3302": "Quarantine File by Hash",
    "RA3303": "Quarantine File by Path",
    "RA3304": "Quarantine File by Content Pattern",
    "RA3401": "Block Process by Executable Path",
    "RA3402": "Block Process by Executable Metadata",
    "RA3403": "Block Process by Executable Hash",
    "RA3404": "Block Process by Executable Format",
    "RA3405": "Block Process by Executable Content Pattern",
    "RA3501": "Disable System Service",
    "RA3601": "Lock User Account",
    "RA4001": "Report Incident to External Companies",
    "RA4101": "Remove Rogue Network Device",
    "RA4201": "Delete Email Message",
    "RA4301": "Remove File",
    "RA4501": "Remove Registry Key",
    "RA4502": "Remove Service",
    "RA4601": "Revoke Authentication Credentials",
    "RA4602": "Remove User Account",
    "RA5001": "Reinstall Host from Golden Image",
    "RA5002": "Restore Data from Backup",
    "RA5101": "Unblock Blocked IP",
    "RA5102": "Unblock Blocked Domain",
    "RA5103": "Unblock Blocked URL",
    "RA5104": "Unblock Blocked Port",
    "RA5105": "Unblock Blocked User",
    "RA5201": "Unblock Domain on Email",
    "RA5202": "Unblock Sender on Email",
    "RA5203": "Restore Quarantined Email Message",
    "RA5301": "Restore Quarantined File",
    "RA5401": "Unblock Blocked Process",
    "RA5501": "Enable Disabled Service",
    "RA5601": "Unlock Locked User Account",
    "RA6001": "Develop Incident Report",
    "RA6002": "Conduct Lessons Learned Exercise"
}
rs_mapping = {
    "RS0001": "Preparation",
    "RS0002": "Identification",
    "RS0003": "Containment",
    "RS0004": "Eradication",
    "RS0005": "Recovery",
    "RS0006": "Lessons Learned"
}