ra_mapping = {
    "RA1101": " Practice",
    "RA1102": " Take trainings",
    "RA1103": " Raise personnel awareness",
    "RA1104": " Make personnel report suspicious activity",
    "RA1105": " Set up relevant data collection",
    "RA1106": " Set up a centralized long-term log storage",
    "RA1107": " Develop communication map",
    "RA1108": " Make sure there are backups",
    "RA1109": " Get network architecture map",
    "RA1110": " Get access control matrix",
    "RA1111": " Develop assets knowledge base",
    "RA1112": " Check analysis toolset",
    "RA1113": " Access vulnerability management system logs",
    "RA1201": " Access external network flow logs",
    "RA1202": " Access internal network flow logs",
    "RA1203": " Access internal HTTP logs",
    "RA1204": " Access external HTTP logs",
    "RA1205": " Access internal DNS logs",
    "RA1206": " Access external DNS logs",
    "RA1207": " Access VPN logs",
    "RA1208": " Access DHCP logs",
    "RA1209": " Access internal packet capture data",
    "RA1210": " Access external packet capture data",
    "RA1211": " Get ability to block external IP address",
    "RA1212": " Get ability to block internal IP address",
    "RA1213": " Get ability to block external domain",
    "RA1214": " Get ability to block internal domain",
    "RA1215": " Get ability to block external URL",
    "RA1216": " Get ability to block internal URL",
    "RA1217": " Get ability to block port external communication",
    "RA1218": " Get ability to block port internal communication",
    "RA1219": " Get ability to block user external communication",
    "RA1220": " Get ability to block user internal communication",
    "RA1301": " Get ability to list users opened email",
    "RA1302": " Get ability to list users received email",
    "RA1303": " Get ability to block email domain",
    "RA1304": " Get ability to block email sender",
    "RA1305": " Get ability to delete email",
    "RA1401": " Get ability to find file by format",
    "RA1402": " Get ability to find file by hash",
    "RA1403": " Get ability to find file by path",
    "RA1404": " Get ability to find file by content pattern",
    "RA1405": " Get ability to find file by metadata",
    "RA1406": " Get ability to find files with tampered timestamps",
    "RA1407": " Get ability to list files modified",
    "RA1408": " Get ability to list files deleted",
    "RA1409": " Get ability to list files downloaded",
    "RA1410": " Get ability to download file from host",
    "RA1411": " Get ability to quarantine file by format",
    "RA1412": " Get ability to quarantine file by hash",
    "RA1413": " Get ability to quarantine file by path",
    "RA1414": " Get ability to quarantine file by content pattern",
    "RA1415": " Get ability to remove file from host",
    "RA1601": " Manage remote computer management system policies",
    "RA2101": " List victims of security alert",
    "RA2102": " List host vulnerabilities",
    "RA2103": " Put compromised accounts on monitoring",
    "RA2201": " List hosts communicated with internal domain",
    "RA2202": " List hosts communicated with internal IP",
    "RA2203": " List hosts communicated with internal URL",
    "RA2204": " Analyse domain name",
    "RA2205": " Analyse IP",
    "RA2206": " Analyse URL",
    "RA2207": " List hosts communicated by port",
    "RA2208": " List hosts connected to VPN",
    "RA2209": " List host connected to intranet",
    "RA2210": " Get data transferred by FTP",
    "RA2211": " Get data transferred by SMB",
    "RA2212": " Get data transferred by HTTP",
    "RA2213": " List hosts communicated with external domain",
    "RA2214": " List hosts communicated with external ip.",
    "RA2215": " List hosts communicated with external URL",
    "RA2301": " List users opened email",
    "RA2302": " Get original email",
    "RA2303": " List email receivers",
    "RA2304": " Make sure email is a phishing",
    "RA2305": " Extract observables from email",
    "RA2401": " List files created",
    "RA2402": " Analyse Windows PE",
    "RA2403": " List processes executed",
    "RA2404": " Analyse filehash",
    "RA2405": " Analyse macos mach-o",
    "RA2406": " Analyse MS office file",
    "RA2407": " Analyse PDF",
    "RA2408": " Analyse Unix ELF",
    "RA2409": " Find file by format",
    "RA2410": " Find file by hash",
    "RA2411": " Find file by path",
    "RA2412": " Find file by content pattern",
    "RA2413": " Find file by metadata",
    "RA2414": " List files modified",
    "RA2415": " List files deleted",
    "RA2416": " List files downloaded",
    "RA2417": " List files with tampered timestamps",
    "RA2418": " Download file from host",
    "RA2501": " List services executed",
    "RA2601": " List registry keys modified",
    "RA3201": " Block external IP address",
    "RA3202": " Block internal IP address",
    "RA3203": " Block external domain",
    "RA3204": " Block internal domain",
    "RA3205": " Block external URL",
    "RA3206": " Block internal URL",
    "RA3207": " Block port external communication",
    "RA3208": " Block port internal communication",
    "RA3209": " Block user external communication",
    "RA3210": " Block user internal communication",
    "RA3301": " Block domain on email",
    "RA3302": " Block sender on email",
    "RA3401": " Quarantine file by format",
    "RA3402": " Quarantine file by hash",
    "RA3403": " Quarantine file by path",
    "RA3404": " Quarantine file by content pattern",
    "RA4101": " Report phishing attack to external companies",
    "RA4102": " Report incident to external companies",
    "RA4301": " Delete email",
    "RA4401": " Remove file from host",
    "RA4701": " Revoke authentication credentials",
    "RA5101": " Reinstall host from golden image",
    "RA6101": " Develop incident report",
    "RA6102": " Conduct lessons learned exercise"
}
rs_mapping = {
    "RS0001": "Preparation",
    "RS0002": "Identification",
    "RS0003": "Containment",
    "RS0004": "Eradication",
    "RS0005": "Recovery",
    "RS0006": "Lessons Learned"
}